<?php
/**
 * AppearanceDataType
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Aurigma\Storefront\Products
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Storefront API - Products
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: storefront-v1-products
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\Storefront\Products\Model;
use \Aurigma\Storefront\Products\ObjectSerializer;

/**
 * AppearanceDataType Class Doc Comment
 *
 * @category Class
 * @description Available appearance types.
 * @package  Aurigma\Storefront\Products
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AppearanceDataType
{
    /**
     * Possible values of this enum
     */
    const RADIO = 'Radio';
    const DROPDOWN = 'Dropdown';
    const CHIPS = 'Chips';
    const COLOR_GRID = 'ColorGrid';
    const COLOR_LIST = 'ColorList';
    const IMAGE_GRID = 'ImageGrid';
    const IMAGE_LIST = 'ImageList';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::RADIO,
            self::DROPDOWN,
            self::CHIPS,
            self::COLOR_GRID,
            self::COLOR_LIST,
            self::IMAGE_GRID,
            self::IMAGE_LIST,
        ];
    }
}


