<?php
/**
 * ProductLinkDto
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Aurigma\Storefront\Products
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Storefront API - Products
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: storefront-v1-products
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\Storefront\Products\Model;

use \ArrayAccess;
use \Aurigma\Storefront\Products\ObjectSerializer;

/**
 * ProductLinkDto Class Doc Comment
 *
 * @category Class
 * @description Dto class, containing information about a product link.
 * @package  Aurigma\Storefront\Products
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ProductLinkDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProductLinkDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'product_version_id' => 'int',
        'product_id' => 'int',
        'storefront_id' => 'int',
        'tenant_id' => 'int',
        'name' => 'string',
        'description' => 'string',
        'tag' => 'string',
        'storefront_product_id' => 'string',
        'storefront_product_name' => 'string',
        'product_filter_id' => 'int',
        'image' => '\Aurigma\Storefront\Products\Model\ImageInfo',
        'product_filter_options' => '\Aurigma\Storefront\Products\Model\ProductFilterOptionDto[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int32',
        'product_version_id' => 'int32',
        'product_id' => 'int32',
        'storefront_id' => 'int32',
        'tenant_id' => 'int32',
        'name' => null,
        'description' => null,
        'tag' => null,
        'storefront_product_id' => null,
        'storefront_product_name' => null,
        'product_filter_id' => 'int32',
        'image' => null,
        'product_filter_options' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'product_version_id' => 'productVersionId',
        'product_id' => 'productId',
        'storefront_id' => 'storefrontId',
        'tenant_id' => 'tenantId',
        'name' => 'name',
        'description' => 'description',
        'tag' => 'tag',
        'storefront_product_id' => 'storefrontProductId',
        'storefront_product_name' => 'storefrontProductName',
        'product_filter_id' => 'productFilterId',
        'image' => 'image',
        'product_filter_options' => 'productFilterOptions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'product_version_id' => 'setProductVersionId',
        'product_id' => 'setProductId',
        'storefront_id' => 'setStorefrontId',
        'tenant_id' => 'setTenantId',
        'name' => 'setName',
        'description' => 'setDescription',
        'tag' => 'setTag',
        'storefront_product_id' => 'setStorefrontProductId',
        'storefront_product_name' => 'setStorefrontProductName',
        'product_filter_id' => 'setProductFilterId',
        'image' => 'setImage',
        'product_filter_options' => 'setProductFilterOptions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'product_version_id' => 'getProductVersionId',
        'product_id' => 'getProductId',
        'storefront_id' => 'getStorefrontId',
        'tenant_id' => 'getTenantId',
        'name' => 'getName',
        'description' => 'getDescription',
        'tag' => 'getTag',
        'storefront_product_id' => 'getStorefrontProductId',
        'storefront_product_name' => 'getStorefrontProductName',
        'product_filter_id' => 'getProductFilterId',
        'image' => 'getImage',
        'product_filter_options' => 'getProductFilterOptions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['product_version_id'] = $data['product_version_id'] ?? null;
        $this->container['product_id'] = $data['product_id'] ?? null;
        $this->container['storefront_id'] = $data['storefront_id'] ?? null;
        $this->container['tenant_id'] = $data['tenant_id'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['description'] = $data['description'] ?? null;
        $this->container['tag'] = $data['tag'] ?? null;
        $this->container['storefront_product_id'] = $data['storefront_product_id'] ?? null;
        $this->container['storefront_product_name'] = $data['storefront_product_name'] ?? null;
        $this->container['product_filter_id'] = $data['product_filter_id'] ?? null;
        $this->container['image'] = $data['image'] ?? null;
        $this->container['product_filter_options'] = $data['product_filter_options'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id Product link identifier.
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets product_version_id
     *
     * @return int|null
     */
    public function getProductVersionId()
    {
        return $this->container['product_version_id'];
    }

    /**
     * Sets product_version_id
     *
     * @param int|null $product_version_id Product version identifier.
     *
     * @return self
     */
    public function setProductVersionId($product_version_id)
    {
        $this->container['product_version_id'] = $product_version_id;

        return $this;
    }

    /**
     * Gets product_id
     *
     * @return int|null
     */
    public function getProductId()
    {
        return $this->container['product_id'];
    }

    /**
     * Sets product_id
     *
     * @param int|null $product_id Product identifier.
     *
     * @return self
     */
    public function setProductId($product_id)
    {
        $this->container['product_id'] = $product_id;

        return $this;
    }

    /**
     * Gets storefront_id
     *
     * @return int|null
     */
    public function getStorefrontId()
    {
        return $this->container['storefront_id'];
    }

    /**
     * Sets storefront_id
     *
     * @param int|null $storefront_id Storefront identifier.
     *
     * @return self
     */
    public function setStorefrontId($storefront_id)
    {
        $this->container['storefront_id'] = $storefront_id;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return int|null
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param int|null $tenant_id Tenant identifier.
     *
     * @return self
     */
    public function setTenantId($tenant_id)
    {
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Product link name.
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Product link description.
     *
     * @return self
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets tag
     *
     * @return string|null
     */
    public function getTag()
    {
        return $this->container['tag'];
    }

    /**
     * Sets tag
     *
     * @param string|null $tag Product link tag.
     *
     * @return self
     */
    public function setTag($tag)
    {
        $this->container['tag'] = $tag;

        return $this;
    }

    /**
     * Gets storefront_product_id
     *
     * @return string|null
     */
    public function getStorefrontProductId()
    {
        return $this->container['storefront_product_id'];
    }

    /**
     * Sets storefront_product_id
     *
     * @param string|null $storefront_product_id Storefront product identifier.
     *
     * @return self
     */
    public function setStorefrontProductId($storefront_product_id)
    {
        $this->container['storefront_product_id'] = $storefront_product_id;

        return $this;
    }

    /**
     * Gets storefront_product_name
     *
     * @return string|null
     */
    public function getStorefrontProductName()
    {
        return $this->container['storefront_product_name'];
    }

    /**
     * Sets storefront_product_name
     *
     * @param string|null $storefront_product_name Storefront product name.
     *
     * @return self
     */
    public function setStorefrontProductName($storefront_product_name)
    {
        $this->container['storefront_product_name'] = $storefront_product_name;

        return $this;
    }

    /**
     * Gets product_filter_id
     *
     * @return int|null
     */
    public function getProductFilterId()
    {
        return $this->container['product_filter_id'];
    }

    /**
     * Sets product_filter_id
     *
     * @param int|null $product_filter_id Product filter identifier.
     *
     * @return self
     */
    public function setProductFilterId($product_filter_id)
    {
        $this->container['product_filter_id'] = $product_filter_id;

        return $this;
    }

    /**
     * Gets image
     *
     * @return \Aurigma\Storefront\Products\Model\ImageInfo|null
     */
    public function getImage()
    {
        return $this->container['image'];
    }

    /**
     * Sets image
     *
     * @param \Aurigma\Storefront\Products\Model\ImageInfo|null $image image
     *
     * @return self
     */
    public function setImage($image)
    {
        $this->container['image'] = $image;

        return $this;
    }

    /**
     * Gets product_filter_options
     *
     * @return \Aurigma\Storefront\Products\Model\ProductFilterOptionDto[]|null
     */
    public function getProductFilterOptions()
    {
        return $this->container['product_filter_options'];
    }

    /**
     * Sets product_filter_options
     *
     * @param \Aurigma\Storefront\Products\Model\ProductFilterOptionDto[]|null $product_filter_options Product filter options.
     *
     * @return self
     */
    public function setProductFilterOptions($product_filter_options)
    {
        $this->container['product_filter_options'] = $product_filter_options;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


